### ISSUE TITLE
Feature: Different settings for each site

### ISSUE THREAD

**Issue by stphnnnn** [biglotteryfund/craft-preview-button#1]
I have a Craft install with multiple sites, each site has it's own frontend URL so ideally I would love a preview button which would allow direct the user to the relevant frontend preview URL.

Is this even possible? I've had a look through the Craft 3 docs and can't seem to find anything on plugin localisation.

**Comment by mattandrews** [comment]
Hi @stphnnnn – great idea. We actually need this feature ourselves as our website has several languages with different URLs. 

I'm not sure either if the docs allow this but it's probably possible to loop through the sites that Craft knows about and generate settings on a per-site basis. Will look into this – watch this space!

**Comment by stphnnnn** [comment]
Any progress on this? I wonder if is could be solved by an input field which works in a similar way to WordPress permalinks.

For example:
https://preview.%domain%/%slug%/

Which would return something like:
https://preview.craftsiteone.com/really-great-post/ 
https://preview.craftsitetwo.com/really-great-post/ 

Using the regular site selection dropdown on entry edit screens already changes the domain but this would allow for using custom subdomains / directories for the preview links

Happy to put together a pull request if you're open to it / think it's a good idea?

**Comment by mattandrews** [comment]
Sorry, this dropped off our radar. Initially I thought [this Stackoverflow thread](https://craftcms.stackexchange.com/questions/20381/plugin-settings-per-site-locale/20382) would help but it's Craft 2 only. 

I like the input field idea you suggest – though using Craft-style variables (`{slug}` rather than `%slug%` etc) feels a bit nicer. That said, it's probably a fair amount of work to write that UI code and safely parse the settings, then pull out the relevant bits of the site domain config and re-assemble it all. 

I've asked [a new SO question](https://craftcms.stackexchange.com/questions/26855/plugin-settings-per-site-locale-craft-3) to see if anyone has a good solution for this (it really feels like something Craft could handle for us), but if nothing comes of it then your solution might work – my proposal earlier (about looping through known sites to generate per-site input fields) may not work as I'm not sure if Craft would support dynamic config like this, so your URL template idea might be the only way to go. 

Thanks for sticking with this!

**Comment by mattandrews** [comment]
Hey @stphnnnn – someone in [my SO question](https://craftcms.stackexchange.com/a/26856) suggested a fix that might work for you without any additional dev work on this plugin:

```
if(Craft::$app->getSites()->getCurrentSite()->handle === X){
    return ['flagName' => 'Tricolore'];
} else {
    return ['flagName' => 'Bundesflagge'];
}
```

That code should let you specify a custom `urlBase` for each site. Does that help?
